CREATE TABLE students (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER,
    pronouns TEXT NOT NULL,
    pet TEXT NOT NULL,
    wandType TEXT NOT NULL,
    wandCore TEXT NOT NULL,
    favoriteSubject TEXT NOT NULL,
    house TEXT NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY(user_id)
            REFERENCES users(id)
);